name: Deploy Function

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      - uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Package and Deploy Function
        run: |
          cd ./function-app
          zip -r ../function-app.zip .
          az functionapp deployment source config-zip \
            --name costoptimizerfunc123 \
            --resource-group cost-optimizer-rg \
            --src ../function-app.zip
          # scm-do-build-during-deployment: true
          # enable-oryx-build: true
          # scm-do-build-during-deployment: false
        
