name: Deploy Function

on:
  push:
    paths:
      - 'function-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd function-app
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      - name: Deploy Function
        uses: Azure/functions-action@v1
        with:
          app-name: costoptimizerfunc123
          package: function-app
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}